#!venv/bin/python
import os
import re
import sys

# Copied from encode/httpcore unasync.py
# https://github.com/encode/httpcore/blob/master/scripts/unasync.py
# Subs modified for farmOS.py

SUBS = [
    ("from farmOS._async", "from farmOS._sync"),
    ("AsyncClient", "Client"),
    ("Async([A-Z][A-Za-z0-9_]*)", r"\2"),
    ("async def", "def"),
    ("async with", "with"),
    ("async for", "for"),
    ("await ", ""),
    ("@pytest.mark.anyio", ""),
]
COMPILED_SUBS = [
    (re.compile(r"(^|\b)" + regex + r"($|\b)"), repl) for regex, repl in SUBS
]


def unasync_line(line):
    for regex, repl in COMPILED_SUBS:
        line = re.sub(regex, repl, line)
    return line


def unasync_file(in_path, out_path):
    with open(in_path, "r") as in_file:
        with open(out_path, "w", newline="") as out_file:
            out_file.write(
                "# AUTO-GENERATED FILE: do not edit manually. Generated by unasync.py.\n"
            )
            for line in in_file.readlines():
                line = unasync_line(line)
                out_file.write(line)


def unasync_file_check(in_path, out_path):
    with open(in_path, "r") as in_file:
        with open(out_path, "r") as out_file:
            out_lines = out_file.readlines()

            # Skip the two header lines we inject into the sync output.
            expected_header = [
                "# AUTO-GENERATED FILE: do not edit manually. Generated by unasync.py.\n",
            ]
            if out_lines[:1] != expected_header:
                print(f"Unexpected header in {out_path!r}")
                print(f"Expected header: {expected_header!r}")
                print(f"Actual header:   {out_lines[:1]!r}")
                sys.exit(1)

            out_data_lines = out_lines[1:]

            for in_line, out_line in zip(in_file.readlines(), out_data_lines):
                expected = unasync_line(in_line)
                if out_line != expected:
                    print(f"unasync mismatch between {in_path!r} and {out_path!r}")
                    print(f"Async code:         {in_line!r}")
                    print(f"Expected sync code: {expected!r}")
                    print(f"Actual sync code:   {out_line!r}")
                    sys.exit(1)


def unasync_dir(in_dir, out_dir, check_only=False):
    for dirpath, dirnames, filenames in os.walk(in_dir):
        for filename in filenames:
            if not filename.endswith(".py"):
                continue
            rel_dir = os.path.relpath(dirpath, in_dir)
            in_path = os.path.normpath(os.path.join(in_dir, rel_dir, filename))
            out_path = os.path.normpath(os.path.join(out_dir, rel_dir, filename))
            print(in_path, "->", out_path)
            if check_only:
                unasync_file_check(in_path, out_path)
            else:
                unasync_file(in_path, out_path)


def main():
    check_only = "--check" in sys.argv
    unasync_dir("farmOS/_async", "farmOS/_sync", check_only=check_only)
    unasync_dir("tests/_async", "tests/_sync", check_only=check_only)


if __name__ == "__main__":
    main()
