name: Run tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # Run at 8AM UTC.
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.9
          - '3.10'
          - 3.11
          - 3.12
          - 3.13
          - 3.14
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Run farmOS development environment containers.
        run: |
          curl https://raw.githubusercontent.com/farmOS/farmOS/4.x/docker/docker-compose.development.yml -o docker-compose.yml
          mkdir www && sudo chown 1000:1000 www
          docker compose up -d
          sleep 5
          sudo mkdir www/keys && sudo chown 1000:1000 www/keys
        env:
          DB_URL: pgsql://farm:farm@db/farm
      - name: Install farmOS
        run: |
          docker compose exec www drush site-install -y --db-url=pgsql://farm:farm@db/farm --account-pass=admin
          docker compose exec www drush en farm_api_default_consumer farm_equipment farm_manager farm_plant farm_observation farm_seeding -y 
          docker compose exec www drush simple-oauth:generate-keys /opt/drupal/keys
          docker compose exec www drush user-create tester --password test
          docker compose exec www drush user-add-role farm_manager tester
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest -e .[test]
      - name: Run farmOS.py tests.
        run: pytest tests
        env:
          FARMOS_HOSTNAME: 'http://localhost'
          FARMOS_OAUTH_USERNAME: 'tester'
          FARMOS_OAUTH_PASSWORD: 'test'
